export const ActionTypes = {
  CREATE_REMAINDER: "CREATE_REMAINDER",
  UPDATE_REMAINDER: "UPDATE_REMAINDER",
  REQUEST_CREATE_REMAINDER: "REQUEST_CREATE_REMAINDER",
  REQUEST_UPDATE_REMAINDER: "REQUEST_UPDATE_REMAINDER",
  EDIT_REMAINDER: "EDIT_REMAINDER",
  SET_ERROR: "SET_ERROR",
  FETCH_WEATHER: "FETCH_WEATHER",
  SET_FILTER: "SET_FILTER"
};

export default ActionTypes;
